DELETE http://localhost:3003/api/blogs/62c17eccc8c2f20f2fd51143
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxnayIsImlkIjoiNjJjMTY4MDc4MTBjZmI3ZWQ5YjI5MDViIiwiaWF0IjoxNjU2ODQ4MDAyfQ.dIKK3xBAUgoBM7ozXiCvGC1eqSm_dJnJ1CWap8MSnaY